openapi: 3.0.3
info:
  title: Rizzlet
  description: This is a competitive, interactive study tool!
  version: 0.1.0
servers:
  - url: http://localhost:8000/api/
tags:
  - name: Questions
  - name: Classes
  - name: Auth
paths:
  /class:
    post:
      tags:
        - Class
      summary: Add a class
      operationId: class
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
            example:
              name: "CSC 308"

        required: true
      responses:
        "200":
          description: Successful operation
          content:
            text/plain; charset=utf-8:
              examples:
                Class CSC 430:
                  value: '"Class CSC 430!"'
        "422":
          description: Validation exception
        "500":
          description: Server Exception
  /hello:
    post:
      tags:
        - hello
      summary: Say hello
      operationId: hello
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
            example:
              name: "Dylan"

        required: true
      responses:
        "200":
          description: Successful operation
          content:
            text/plain; charset=utf-8:
              examples:
                My name is Dylan:
                  value: '"My name is Dylan!"'
        "422":
          description: Validation exception
        "500":
          description: Server Exception
  /question:
    post:
      tags:
        - Questions
      description: Add a given question to the database
      operationId: addQuestion
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Question"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
        "422":
          description: Validation exception
        "500":
          description: Server Exception
    get:
      tags:
        - Questions
      description: Get all questions
      operationId: getAllQuestions
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                  items:
                    $ref: "#/components/schemas/Question"
        "422":
          description: Validation exception
        "500":
          description: Server Exception
  /auth/google:
    post:
      tags:
        - Auth
      description: Try to login with google's auth code
      operationId: authGoogle
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                authorizationCode:
                  type: string
        required: true
      responses:
        "200":
          description: Auth Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  firstName:
                    type: string
                  lastName:
                    type: string
                  email:
                    type: string
                  id:
                    type: string
                  sub:
                    type: string
        "400":
          description: Auth code validation error
        "422":
          description: Validation exception
        "500":
          description: Server exception

components:
  schemas:
    Question:
      required:
        - question
        - answer
      type: object
      properties:
        type:
          type: string
          enum:
            - true/false
        question:
          type: string
        answer:
          type: boolean
